export {default as LoginCalendar} from "./prelogin-icons/calendar.svg"
export {default as LoginTreatment} from "./prelogin-icons/treatment.svg"
export {default as LoginCheckin} from "./prelogin-icons/checkin.svg"
export {default as LoginCare} from "./prelogin-icons/care.svg"
export {default as LoginChat} from "./prelogin-icons/chat.svg"
//side nav
export {default as logo} from "./postlogin-icons/sidenav/logo.svg"
export {default as drawer} from "./postlogin-icons/sidenav/drawer.svg"
export {default as dashboardIcon} from "./postlogin-icons/sidenav/dashboard-icon.svg"
export {default as graphIcon} from "./postlogin-icons/sidenav/graph-icon.svg"
export {default as historyIcon} from "./postlogin-icons/sidenav/history-icon.svg"
export {default as hospitalIcon} from "./postlogin-icons/sidenav/hospital-icon.svg"
export {default as organizationIcon} from "./postlogin-icons/sidenav/organization-icon.svg"
export {default as powerIcon} from "./postlogin-icons/sidenav/power-icon.svg"
export {default as setting2Icon} from "./postlogin-icons/sidenav/settings-2-icon.svg"
export {default as settingsIcon} from "./postlogin-icons/sidenav/settings-icon.svg"
export {default as profileIcon} from "./postlogin-icons/sidenav/profile-icon.svg"
